export const GET_ARTICLE_LIST = 'GET_ARTICLE_LIST';

//리듀서 액션타입을 다 1페이지로 모으고 export함
export const GET_ARTICLE_LIST_REQUSET = 'GET_ARTICLE_LIST_REQUSET';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAILED = 'GET_ARTICLE_LIST_FAILED';


export const DELETE_ARTICLE_LIST = 'DELETE_ARTICLE_LIST';
export const DELETE_ARTICLE_LIST_REQUSET = 'DELETE_ARTICLE_LIST_REQUSET';
export const DELETE_ARTICLE_LIST_SUCCESS = 'DELETE_ARTICLE_LIST_SUCCESS';
export const DELETE_ARTICLE_LIST_FAILED = 'DELETE_ARTICLE_LIST_FAILED';
